sonar.projectKey=sqp_e90e3ad557069fae5f14b5f028012be468d82c12
sonar.projectName=EmployeeManagementSystem
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.java.binaries=target/classes
