sonar.projectKey=sqa_8d202cc929a61895df671b4218941c09e459e80a
sonar.projectName=EmployeeManagementSystem
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.java.binaries=target/classes
